### ISSUE TITLE
Local Link errors in PEBakery Helpfiles

### ISSUE THREAD

**Issue by willi-neu9** [pebakery/pebakery-docs#1]
There are many (more than 100) local cross link errors in the PeBakery help files that make it impossible to use these links with FireFox and addons "Markdown Viewer Webtext" or with "Gitlab Markdown Viewer" when help files are stored locally.

Some of these links are totally not available (see attached file "notfound.txt"). Others have wrong relative paths, missing extension ".md" or are mistyped (see attached file: "modified.txt").

E.g.: If you click on help page "variables" at end of page on "Related: AddVariables" then nothing happens, because the related link in file: "LangRef\Variables.md" is wrong.

"/Commands/Control/AddVariables.md" has an absolute path but must have:
"../Commands/Control/AddVariables.md" to be found by "Markdown Viewer Webtext" and FireFox.

The attached program "Markdown" searches recursive through the PeHelpfiles and corrects the link destination if possible.

It would be fine if you can correct these lokal link issues in the future.

Best regards

/Willi/

Modifikation: 

MARKDOWN.EXE has been modified to correct some additional entries that are not recognized before due a syntax variation in Markdown file link.

Hope it helps.

/Willi/

[markdown_v101.zip](https://github.com/pebakery/pebakery-docs/files/5888186/markdown_v101.zip)
[modified.txt](https://github.com/pebakery/pebakery-docs/files/5888187/modified.txt)
[notfound.txt](https://github.com/pebakery/pebakery-docs/files/5888188/notfound.txt)

**Comment by homes32** [comment]
Thanks for the detailed report! I did not anticipate using a local viewer and lazily wrote them for web browsing. I'll get them fixed up.

cheers!
Homes32

**Comment by homes32** [comment]
A very handy tool. thanks again for sharing and reporting!

**Comment by willi-neu9** [comment]
Hi Jonathan,

MARKDOWN is specialy written for me, for you and the community.

On the other hand PEBakery is really a great tool that helps me very
much creating an emergency windows based on the work of the German journal c’t.

I’ve really used this emergency windows very much in the past keeping
my computers alive.

So thanks back to you for creating and maintaining PEBakery.

/Willi/
